plugins {
    id 'com.gtnewhorizons.retrofuturagradle' version '1.3.27'
}
group = 'com.animstudio'
version = '1.0.0'
archivesBaseName = 'AnimStudio'
minecraft {
    mcVersion = '1.7.10'
    username = 'Player'
}
repositories {
    mavenCentral()
    maven { url 'https://maven.minecraftforge.net' }
}
dependencies {}
processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', minecraft.mcVersion
    filesMatching('mcmod.info') {
        expand 'version': project.version, 'mcversion': minecraft.mcVersion
    }
}
